// Run after editing web assets: node web/build-cache.cjs
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = __dirname;
function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
    const file = path.join(dir, entry.name);
    return entry.isDirectory() ? (entry.name === 'tests' ? [] : walk(file)) : [file];
  });
}
const files = walk(root).filter(f => /\.(html|js|css|ico|png|woff2)$/i.test(f) && path.basename(f) !== 'sw.js').sort();
const hash = crypto.createHash('sha256');
for (const file of files) hash.update(path.relative(root, file)).update(fs.readFileSync(file));
const version = hash.digest('hex').slice(0, 16);
const assets = files.map(f => './' + path.relative(root, f).split(path.sep).map(encodeURIComponent).join('/'));
fs.writeFileSync(path.join(root, 'sw.js'), `// Generated by tools/build-web-cache.cjs; rebuild after asset changes.
const PREFIX = 'azhs-static-' + encodeURIComponent(self.registration.scope) + '-';
const CACHE = PREFIX + '${version}';
const ASSETS = ${JSON.stringify(assets, null, 2)};
const allowed = new Set(ASSETS.map(p => new URL(p, self.registration.scope).href));
self.addEventListener('install', event => {
  // Atomic install: a failed download leaves the previous working version active.
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS.map(p => new Request(new URL(p, self.registration.scope), {cache: 'reload'})))));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith(PREFIX) && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  url.search = ''; url.hash = '';
  if (url.href === self.registration.scope) url.pathname += 'index.html';
  if (!allowed.has(url.href)) return;
  event.respondWith(caches.open(CACHE).then(async cache => {
    const hit = await cache.match(url.href);
    if (hit) return hit;
    const response = await fetch(event.request);
    if (response.ok && response.type === 'basic') await cache.put(url.href, response.clone());
    return response;
  }));
});
`);
console.log(`Generated cache ${version}: ${assets.length} assets`);

