// Generated by tools/build-web-cache.cjs; rebuild after asset changes.
const PREFIX = 'azhs-static-' + encodeURIComponent(self.registration.scope) + '-';
const CACHE = PREFIX + '8fd6833944dea8f9';
const ASSETS = [
  "./Encrypted.JS",
  "./KaTeX_Main-Regular.woff2",
  "./KaTeX_Math-Italic.woff2",
  "./algebrite.bundle-for-browser.js",
  "./az-128.ico",
  "./az_local.js",
  "./az_pen.js",
  "./az_server_jx.js",
  "./az_simplify.js",
  "./az_url.js",
  "./cache-register.js",
  "./dc.JS",
  "./fx.png",
  "./gi.CSS",
  "./index.html",
  "./katex.min.css",
  "./katex.min.js",
  "./la.js",
  "./math.js",
  "./nerdamer.algebra.js",
  "./nerdamer.calculus.js",
  "./nerdamer.core.js",
  "./nerdamer.solve.js",
  "./q/mathscribe/jqmath-0.4.3.css",
  "./s.js",
  "./simplifier%20(1).html",
  "./welcome.html",
  "./%E7%94%A8%E6%88%B7%E6%96%87%E6%A1%A3.html"
];
const allowed = new Set(ASSETS.map(p => new URL(p, self.registration.scope).href));
self.addEventListener('install', event => {
  // Atomic install: a failed download leaves the previous working version active.
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS.map(p => new Request(new URL(p, self.registration.scope), {cache: 'reload'})))));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith(PREFIX) && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  url.search = ''; url.hash = '';
  if (url.href === self.registration.scope) url.pathname += 'index.html';
  if (!allowed.has(url.href)) return;
  event.respondWith(caches.open(CACHE).then(async cache => {
    const hit = await cache.match(url.href);
    if (hit) return hit;
    const response = await fetch(event.request);
    if (response.ok && response.type === 'basic') await cache.put(url.href, response.clone());
    return response;
  }));
});
